# Generated by Django 4.2.4 on 2023-08-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_linkbox_sitesettings_copy_right_text_links'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderhome',
            name='image',
            field=models.ImageField(upload_to='uploads/images/slider_images'),
        ),
    ]
