# Generated by Django 4.2.4 on 2023-08-25 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_sliderhome_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderhome',
            name='image',
            field=models.ImageField(upload_to='images/slider_images'),
        ),
    ]
